-- user : 회원
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `no` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '회원번호',
  `id` VARCHAR(64) NOT NULL UNIQUE COMMENT '아이디',
  `username` VARCHAR(100) NOT NULL COMMENT '사용자명',
  `password` VARCHAR(200) NOT NULL COMMENT '비밀번호',
  `name` VARCHAR(100) NOT NULL COMMENT '이름',
  `email` VARCHAR(200) DEFAULT NULL COMMENT '이메일',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `enabled` INT DEFAULT 1 COMMENT '활성화여부'
) COMMENT='회원';

SELECT * FROM `user`;