-- user_auth : 회원권한
DROP TABLE IF EXISTS `user_auth`;
CREATE TABLE `user_auth` (
  `no` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '권한번호',
  `id` VARCHAR(64) NOT NULL COMMENT '사용자ID (UK)',
  `username` VARCHAR(100) NOT NULL COMMENT '사용자명',
  `auth` VARCHAR(100) NOT NULL COMMENT '권한 (ROLE_USER, ROLE_ADMIN, ...)',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시'
) COMMENT='회원권한';